# Generated by Django 2.0.7 on 2018-07-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IO_Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='io',
            name='input_type',
            field=models.CharField(choices=[('TPN', 'TPN'), ('LIP', 'Lipids'), ('ENT', 'Enteral Feeds'), ('BOT', 'Bottle Feeds'), ('MED', 'Medications'), ('URI', 'Urine'), ('POO', 'Poop'), ('EME', 'Emesis'), ('GAS', 'Gastric Output')], default='TPN', max_length=3),
        ),
        migrations.AlterField(
            model_name='io',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
