# Generated by Django 2.0.7 on 2018-08-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IO_Tracker', '0002_auto_20180730_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='io',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
