# Generated by Django 2.0.7 on 2018-08-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IO_Tracker', '0004_auto_20180810_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='io',
            name='poopFlag',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='io',
            name='urineFlag',
            field=models.NullBooleanField(default=None),
        ),
    ]
