# Generated by Django 2.0.7 on 2018-08-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IO_Tracker', '0005_auto_20180811_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='io',
            name='test',
            field=models.TextField(blank=True),
        ),
    ]
