# Generated by Django 2.0.7 on 2018-08-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IO_Tracker', '0006_io_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='io',
            name='poopFlag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='io',
            name='urineFlag',
            field=models.BooleanField(default=False),
        ),
    ]
